"""refactor_user_customer_structure_v4

Revision ID: 1271cb2c6614
Revises: f4e85e2da037
Create Date: 2025-10-09 21:36:06.397488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1271cb2c6614'
down_revision: Union[str, Sequence[str], None] = 'f4e85e2da037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'full_name')
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    op.add_column('customers', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
