"""fix-customer-models

Revision ID: 179d2244ce89
Revises: 6d39e6ba3dce
Create Date: 2025-10-11 19:49:05.411140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "179d2244ce89"
down_revision: Union[str, Sequence[str], None] = "6d39e6ba3dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "full_name")
    # ### end Alembic commands ###
