"""Add full_name to staff_profile model

Revision ID: 2b3588457038
Revises: dde5fef4d795
Create Date: 2025-10-13 20:52:52.998722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2b3588457038"
down_revision: Union[str, Sequence[str], None] = "dde5fef4d795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "staff_profile",
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "full_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("staff_profile", "full_name")
    # ### end Alembic commands ###
