"""create service and category tables 2

Revision ID: 3d4155c8898f
Revises: 0bd3cf57a1a9
Create Date: 2025-09-29 19:52:50.000661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3d4155c8898f"
down_revision: Union[str, Sequence[str], None] = "0bd3cf57a1a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_category_id"), "service_category", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_service_category_is_deleted"),
        "service_category",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_category_name"), "service_category", ["name"], unique=True
    )
    op.create_table(
        "service",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "preparation_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "aftercare_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "contraindications", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_id"), "service", ["id"], unique=False)
    op.create_index(
        op.f("ix_service_is_deleted"), "service", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_service_name"), "service", ["name"], unique=True)
    op.create_table(
        "service_image",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alt_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_image_id"), "service_image", ["id"], unique=False)
    op.create_index(
        op.f("ix_service_image_is_deleted"),
        "service_image",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_image_is_deleted"), table_name="service_image")
    op.drop_index(op.f("ix_service_image_id"), table_name="service_image")
    op.drop_table("service_image")
    op.drop_index(op.f("ix_service_name"), table_name="service")
    op.drop_index(op.f("ix_service_is_deleted"), table_name="service")
    op.drop_index(op.f("ix_service_id"), table_name="service")
    op.drop_table("service")
    op.drop_index(op.f("ix_service_category_name"), table_name="service_category")
    op.drop_index(op.f("ix_service_category_is_deleted"), table_name="service_category")
    op.drop_index(op.f("ix_service_category_id"), table_name="service_category")
    op.drop_table("service_category")
    # ### end Alembic commands ###
