"""add_is_email_verified_to_user

Revision ID: 46cbaa4ca32e
Revises: cd4cba7e2e2c
Create Date: 2025-09-24 20:27:50.408758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46cbaa4ca32e"
down_revision: Union[str, Sequence[str], None] = "cd4cba7e2e2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_email_verified")
    # ### end Alembic commands ###
