"""add_owner_to_image

Revision ID: 6d39e6ba3dce
Revises: aed7bab709c3
Create Date: 2025-10-10 16:44:28.039651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6d39e6ba3dce"
down_revision: Union[str, Sequence[str], None] = "aed7bab709c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_image_uploaded_by_user_id"),
        "image",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_foreign_key(None, "image", "user", ["uploaded_by_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image", type_="foreignkey")
    op.drop_index(op.f("ix_image_uploaded_by_user_id"), table_name="image")
    op.drop_column("image", "uploaded_by_user_id")
    # ### end Alembic commands ###
