"""Add full_name to staff_profile model v2

Revision ID: 869b92b08ef2
Revises: 2b3588457038
Create Date: 2025-10-13 21:45:53.657875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "869b92b08ef2"
down_revision: Union[str, Sequence[str], None] = "2b3588457038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.create_unique_constraint(None, "customers", ["user_id"])
    op.drop_column("customers", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "customers", type_="unique")
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=True)
    op.drop_column("customers", "note")
    # ### end Alembic commands ###
