"""Remove user_type from User model

Revision ID: aed7bab709c3
Revises: 1271cb2c6614
Create Date: 2025-10-10 12:30:09.139170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "aed7bab709c3"
down_revision: Union[str, Sequence[str], None] = "1271cb2c6614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_type"), table_name="user")
    op.drop_column("user", "user_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("user_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_user_user_type"), "user", ["user_type"], unique=False)
    # ### end Alembic commands ###
