"""refactor_user_customer_structure_v2

Revision ID: b006bdd9b8a9
Revises: a19b4f512f01
Create Date: 2025-10-09 21:06:10.697493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b006bdd9b8a9"
down_revision: Union[str, Sequence[str], None] = "a19b4f512f01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("customers", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("customers", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
