"""update user table

Revision ID: cd4cba7e2e2c
Revises: 0a452aba41ed
Create Date: 2025-09-24 19:40:28.904397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cd4cba7e2e2c"
down_revision: Union[str, Sequence[str], None] = "0a452aba41ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_user_phone"), "user", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_phone"), table_name="user")
    op.drop_column("user", "phone")
    # ### end Alembic commands ###
