"""Add staff management module

Revision ID: dde5fef4d795
Revises: ecdde6ec4028
Create Date: 2025-10-13 16:35:36.173596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dde5fef4d795"
down_revision: Union[str, Sequence[str], None] = "ecdde6ec4028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "staff_profile", "position", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "staff_profile", "hire_date", existing_type=sa.DATE(), nullable=True
    )
    op.drop_index(op.f("ix_staff_profile_phone_number"), table_name="staff_profile")
    op.create_index(
        op.f("ix_staff_profile_phone_number"),
        "staff_profile",
        ["phone_number"],
        unique=True,
    )
    op.drop_column("staff_profile", "skills_summary")
    op.drop_column("staff_schedule", "is_recurring")
    op.alter_column(
        "staff_time_off", "reason", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "staff_time_off", "reason", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "staff_schedule",
        sa.Column("is_recurring", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "staff_profile",
        sa.Column("skills_summary", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_staff_profile_phone_number"), table_name="staff_profile")
    op.create_index(
        op.f("ix_staff_profile_phone_number"),
        "staff_profile",
        ["phone_number"],
        unique=False,
    )
    op.alter_column(
        "staff_profile", "hire_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "staff_profile",
        "position",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
