"""create default schedule table

Revision ID: f16da994918a
Revises: 3d4155c8898f
Create Date: 2025-10-01 19:56:27.224947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f16da994918a"
down_revision: Union[str, Sequence[str], None] = "3d4155c8898f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_default_schedule_id"), "default_schedule", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_default_schedule_is_deleted"),
        "default_schedule",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_schedule_user_id"),
        "default_schedule",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_default_schedule_user_id"), table_name="default_schedule")
    op.drop_index(op.f("ix_default_schedule_is_deleted"), table_name="default_schedule")
    op.drop_index(op.f("ix_default_schedule_id"), table_name="default_schedule")
    op.drop_table("default_schedule")
    # ### end Alembic commands ###
